import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useEffect, useState } from "react"

import { Chart } from "react-google-charts"

import { processData } from '../lib/process-data'

import Title from '../components/title'

export default function Home() {

  const [artistsData, setArtistsData] = useState({});
  const [tracksData, setTracksData] = useState({});

  useEffect(() => {

    const { artistsData, tracksData } = processData();

    setArtistsData(artistsData);
    setTracksData(tracksData);

  }, []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify 2021</title>
        <meta name="description" content="Spotify App Generated by create next app" />
      </Head>
      <Title
        section={"Artists"}
      />
      <Chart
          width={'1300px'}
          height={'800px'}
          chartType="Bar"
          loader={<div>Loading Chart</div>}
          data={artistsData}
          options={{
            // Material design options
            colors: ['#E4BAD4'],
            chart: {
              title: 'Spotify 2021',
            },
          }}
      />
      <Title
        section={"Tracks"}
      />
      <Chart
          width={'1300px'}
          height={'800px'}
          chartType="Bar"
          loader={<div>Loading Chart</div>}
          data={tracksData}
          options={{
            // Material design options
            colors: ['#B8E4F0'],
            chart: {
              title: 'Spotify 2021',
            },
          }}
      />
    </div>
  )
}
