import Head from 'next/head'
import { useState } from "react"

import Box from '@mui/material/Box'
import Tab from '@mui/material/Tab'
import {TabContext, TabList, TabPanel} from '@material-ui/lab'
import { MicExternalOn, Audiotrack, BarChart } from '@mui/icons-material'

import styles from '../styles/Home.module.css'

import TabsBox from '../components/tabs-box'
import Banner from '../components/banner'
import ArtistsSection from '../components/artists-section'
import SongsSection from '../components/songs-section'
import GoogleChart from '../components/googleChart'

import { processData } from '../lib/process-data'

export default function Home() {
  const {
    artists, tracks, artistsData, songsData, artistsDataByTime, songsDataByTime
  } = processData(2024);

  const [value, setValue] = useState("1");

  const handleChangeMenu = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <div className={styles.container}>
      <div className={styles.navBar}>
        <Head>
          <title>Spotify Data</title>
          <meta name="description" content="Spotify App Generated by create next app" />
        </Head>
      </div>
      <div className={styles.informationContainer}>
        <div className={styles.dataContainer}>
          <Box>
            <TabContext sx={{ backgroundColor: "white"}} value={value}>
              <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                <TabList onChange={handleChangeMenu}>
                  <Tab icon={<MicExternalOn />} value="1" />
                  <Tab icon={<Audiotrack />} value="2" />
                  <Tab label={<BarChart />} value="3" />
                </TabList>
              </Box>
              <TabPanel value="1">
                <div className={styles.tabPanelContainer}>
                  <Banner
                    title={"Top Artistas"}
                  />
                  <TabsBox
                    section={"artists"}
                  />
                  <ArtistsSection
                    dataArtists={artistsData}
                    dataArtistsByTime={artistsDataByTime}
                  />
                </div>
              </TabPanel>
              <TabPanel value="2">
                <Banner
                  title={"Top Canciones"}
                />
                <TabsBox
                  section={"songs"}
                />
                <SongsSection
                    dataTracks={songsData}
                    dataTracksByTime={songsDataByTime}
                />
              </TabPanel>
              <TabPanel value="3">
                <GoogleChart
                  width="1500px"
                  height="800px"
                  chartType="Bar"
                  color="#F6C6EA"
                  data={artists.slice(0,20)}
                />
                <GoogleChart
                  width="1500px"
                  height="800px"
                  chartType="Bar"
                  color="#BFA2DB"
                  data={tracks.slice(0,20)}
                />
              </TabPanel>
            </TabContext>
          </Box>
        </div>
      </div>
    </div>
  )
}
